services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: shop
      MARIADB_USER: shopping
      MARIADB_PASSWORD: site
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: php
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    volumes:
      - phpmyadmin-data:/sessions
  php:
    image: nyanzo/phptest-buster:latest
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  selenium-chrome:
    image: nyanzo/selenium-local:latest
    ports:
      - 4444:4444
      - 5900:5900

volumes:
  db-data:
  phpmyadmin-data:
